language: node_js
node_js:
  - "7"
dist: trusty
sudo: false
addons:
  chrome: stable
git:
  depth: 1
cache:
  yarn: false
  directories:
    - node_modules
# before_install:
#   - # start your web application and listen on `localhost:3000`
#   - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost:3000
before-script:
  - npm install
script:
  - npm run test
